#!/bin/bash

sudo iptables -A INPUT -s 192.168.1.100 -d 192.168.1.10 -p tcp --dport 22 -j Accect

sudo iptables -F

sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -A OUTPUT -p tcp -dport 22 -j ACCEPT






